[package]
name = "temper-usb"
version = "0.1.0"
edition = "2018"

[dependencies]
rusb = "0.9"
actix-web = "3"
paho-mqtt = "0.9"
sd-notify = "0.3"
clap = "2.33"
anyhow = "1.0"
fork = "0.1"

[profile.release]
lto = true

